<?php

namespace drieschel\batches;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-06-05 at 15:24:02.
 */
class BatchTest extends \PHPUnit_Framework_TestCase
{

  /**
   * @var Batch
   */
  protected $object;

  /**
   * @var string
   */
  protected $runFilesDir;
  
  /**
   * @var string 
   */
  protected $runFilename = 'batch_test';
  
  /**
   * @var string
   */
  protected $runFile;
  
  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->runFilesDir = __DIR__ . '/runFiles';
    $this->runFile = $this->runFilesDir . '/' . $this->runFilename;
    if(is_file($this->runFile))
    {
      unlink($this->runFile);
    }   
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {

  }

  /**
   * @covers drieschel\batches\Batch::run
   */
  public function testFirstRun()
  {    
    $batch = new Batch('test', $this->runFilesDir);
    $jobMock = $this->getMockBuilder('\\drieschel\\batches\\Job')->getMock();
    $batch->addJob($jobMock);
    $batch->run();    
    $this->assertTrue(is_file($this->runFile));
  }
  /**
   * @covers drieschel\batches\Batch::run
   */
  public function testRunWithIntervalTimeExceeded()
  {
    $lastModifyDate = new \DateTime('2015-01-01');
    touch($this->runFile, $lastModifyDate->getTimestamp());
    $jobMock = $this->getMockBuilder('\\drieschel\\batches\\Job')->getMock();
    $batch = new Batch('test', $this->runFilesDir);    
    $batch->executionPlan('*', '*', '1', '0', '0');
    $batch->addJob($jobMock);
    $now = new \DateTime();
    $batch->run();
    clearstatcache();
    $lastRunTime = filemtime($this->runFile);
    $this->assertTrue($lastRunTime >= $now->getTimestamp());
  }
  
  /**
   * @covers drieschel\batches\Batch::run
   */
  public function testRunWithLastRunInPastButInInterval()
  {
    $halfHourAgo = new \DateTime('@' . (time() - 1800));    
    $oneHourAgo = new \DateTime('@' . (time() - 3600));
    touch($this->runFile, $halfHourAgo->getTimestamp());
    $jobMock = $this->getMockBuilder('\\drieschel\\batches\\Job')->getMock();
    $batch = new Batch('test', $this->runFilesDir);
    $batch->executionPlan('*', '*', '*', $oneHourAgo->format('m'), '0');
    $batch->addJob($jobMock);
    $batch->run();
    $oldTime = $halfHourAgo->getTimestamp();
    clearstatcache();
    $newTime = filemtime($this->runFile);
    $this->assertTrue($oldTime === $newTime);
  }
  /**
   * @covers drieschel\batches\Batch::run
   */
  public function testRunWithExecutionDateReached()
  {
    $halfHourAgo = new \DateTime('@' . (time() - 1800));
    $oneHourAgo = new \DateTime('@' . (time() - 3600));
    touch($this->runFile, $oneHourAgo->getTimestamp());
    $jobMock = $this->getMockBuilder('\\drieschel\\batches\\Job')->getMock();
    $batch = new Batch('test', $this->runFilesDir);
    $batch->executionPlan('*', '*', '*', $halfHourAgo->format('m'), '0');
    $batch->addJob($jobMock);
    $now = new \DateTime();    
    $batch->run();
    clearstatcache();
    $lastRunTime = filemtime($this->runFile);
    $this->assertTrue($lastRunTime >= $now->getTimestamp());
  }

}
